#!/bin/bash

#------------------------------------------------------------------------------------
# Params
#------------------------------------------------------------------------------------

echo -e "What is the server domain: \c "
read DOMAIN

echo -e "What is the server name (subdomain): \c "
read SERVER_NAME

echo -e "What is the mail subdomain: \c "
read MAIL_DOMAIN

echo -e "What is the admin email: \c "
read ADMIN_EMAIL

echo -e "What is the default user: \c "
read USER



#------------------------------------------------------------------------------------
# Vars
#------------------------------------------------------------------------------------

MYSQL_DEFAULT_PASS=a
FTP_DEFAULT_PASS=a

#------------------------------------------------------------------------------------
# Setup
#------------------------------------------------------------------------------------

yum -y update
yum -y install wget

[ ! -d ~/scripts  ] && mkdir ~/scripts

cd ~/scripts

#------------------------------------------------------------------------------------
# Install apache
#------------------------------------------------------------------------------------

wget https://raw.githubusercontent.com/samuelbirch/webserver/master/apache.sh
bash apache.sh $SERVER_NAME.$DOMAIN $ADMIN_EMAIL

#------------------------------------------------------------------------------------
# Install php
#------------------------------------------------------------------------------------

wget https://raw.githubusercontent.com/samuelbirch/webserver/master/php.sh
bash php.sh

#------------------------------------------------------------------------------------
# Install db
#------------------------------------------------------------------------------------

wget https://raw.githubusercontent.com/samuelbirch/webserver/master/db.sh
MYSQL_DEFAULT_PASS=$(bash db.sh $USER)

#------------------------------------------------------------------------------------
# Install ftp
#------------------------------------------------------------------------------------

wget https://raw.githubusercontent.com/samuelbirch/webserver/master/ftp.sh
FTP_DEFAULT_PASS=$(bash ftp.sh $USER)

#------------------------------------------------------------------------------------
# Install fail2ban
#------------------------------------------------------------------------------------

wget https://raw.githubusercontent.com/samuelbirch/webserver/master/fail2ban.sh
bash fail2ban.sh

#------------------------------------------------------------------------------------
# Install firewall
#------------------------------------------------------------------------------------

wget https://raw.githubusercontent.com/samuelbirch/webserver/master/firewall.sh
bash firewall.sh

#------------------------------------------------------------------------------------
# Install mail
#------------------------------------------------------------------------------------

wget https://raw.githubusercontent.com/samuelbirch/webserver/master/mail.sh
bash mail.sh $DOMAIN $MAIL_DOMAIN

#------------------------------------------------------------------------------------
# Download vhost
#------------------------------------------------------------------------------------

wget https://raw.githubusercontent.com/samuelbirch/webserver/master/vhost.sh

#------------------------------------------------------------------------------------
# Output
#------------------------------------------------------------------------------------

echo "All done! Your MYSQL password is $MYSQL_DEFAULT_PASS"
echo "Your FTP root password is $FTP_DEFAULT_PASS"