#!/bin/bash

#------------------------------------------------------------------------------------
# Params
#------------------------------------------------------------------------------------

DOMAIN=$1
if [ -z "$DOMAIN" ] 
then
	echo -e "What is the server domain: \c "
	read DOMAIN
fi

MAIL_DOMAIN=$2
if [ -z ${MAIL_DOMAIN+x} ]; then
	echo -e "What is the mail subdomain: \c "
	read MAIL_DOMAIN
fi

#------------------------------------------------------------------------------------
# Install postfix
#------------------------------------------------------------------------------------

#yum -y install postfix

